# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Amau Medicina
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Medicina de Corazon a Corazon
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amaumedicina.com"

defaults:
  - scope:
      path: "gallery"
    values:
      image: true

# Build settings
markdown: kramdown
sass:
  sass_dir: _scss
#theme: minima
include: ['_layouts']
plugins:
  - jekyll-feed

host: 0.0.0.0

exclude:
  - package.json
  - package-lock.json
  - startfile.sh
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scss
  - _layouts